### PR TITLE
Add issue templates

### PR DESCRIPTION
**Pull request by dtivel**
CC @clairernovotny

### CODE REVIEW

**Comment by erdembayar** [comment]
Probably need 2 more sections too, maybe next time.
image

**Review by clairernovotny — APPROVED** [review]

**Comment by skofman1** [comment]
@dtivel , @clairernovotny , please take a look at @erdembayar comment above.

**Comment by clairernovotny** [comment]
Merged to get the first two available for email templates. We can come back to address the gaps in another PR.

**Comment by dtivel** [comment]
Thanks for the feedback, @erdembayar.  We get the "Report a security vulnerability" option for free.

image

**Pull request merged**
